### ISSUE TITLE
User account

### ISSUE THREAD

**Issue by samseaver** [ModelSEED/Model-SEED-core#106]
It seems that ModelSEEDCore now has the functionality of retrieving authentication from the central SEED server, which seems useful if you have created an account.  This works, when, upon starting over with no user account, I used the same username and password as my SEED account.  However:

1) It won't access the server unless you're on an Argonne network or using a computer
2) It seems to log me out automatically after sometime, so if there is a sufficient delay between making changes to a program, I have to log back in again.

I "fixed" this by creating my account again using ms-createuser, but the issue remains.

**Comment by samseaver** [comment]
Also, I just found out again, I think this could have been stated in a previous issue, that my user id number has reverted to '1'.  I can modify it within the USERS table, but I'm not sure if the issue of user ids has been covered recently?

**Comment by cshenry** [comment]
If you create your own account using createuser, it will reset your user id. You shouldn't do this. We should find a way to make the account import work properly. Frankly, I'm tempted to delete the createuser function, because I really don't want people making user accounts this way.

I'm also really confused about why the account import isn't working. I know it works from any location on the internet (I've used it from home without VPN). You don't need to be on the Argonne network.Or at least, this is how it's supposed to work. Are you sure about this?

It should never ever log you out automatically. That is very strange. It seems like you're discovering a couple of edge cases... not sure what's happening.

**Comment by samseaver** [comment]
I no longer have any trouble with this, and I tested it with a brand new clone of the repository
