### ISSUE TITLE
the bootstrap shell script

### ISSUE THREAD

**Issue by raphyz** [ModelSEED/Model-SEED-core#21]
The first problem with this scirpt is that you need to clone the repository in order to see it, and it clones the repository with it.

The git clone command does not work for me for some reason, and I had to change the git clone command to: git clone https://user_name@github.com/ModelSEED/Model-SEED-core $INSTALL_DIR;

where user_name was changed to my user name.

I wonder if this will only be my problem.

**Comment by samseaver** [comment]
I think the issue you had with the git clone command might be that you have to save your public ssh key in your profile, have you done that?

Is there a neutral way for a user to `git clone` a public repository without even have to register as an account user?

**Comment by raphyz** [comment]
I have saved the ssh key,I think that this is not a problem.

I used https instead and it worked.

**Comment by devoid** [comment]
So the idea of this script is that it would be made available outside the repository for users to quickly get up and running. However it should be _in the repository_ because it's code that we want to track and manage.

As for your git clone issue: one possibility is that I left off the `.git` suffix. If you do:

```
git clone git://github.com/ModelSEED/Model-SEED-core.git dir
```

Does that work? I'd be ok switching to the https or ssh version, but for these I think the user needs a github account.

**Comment by samseaver** [comment]
Yea

git clone git://github.com/ModelSEED/Model-SEED-core.git dir

works for me.

**Comment by devoid** [comment]
Seems to work now. Reopen if there's an issue.
