### ISSUE TITLE
new install problems 

### ISSUE THREAD

**Issue by raphyz** [ModelSEED/Model-SEED-core#35]
Hi

I have started from scratch again the installation of the project (Model-SEED-core)

I decided that I will try to work with sqlite so that I will have less problems,

however I still have problems.

Here they are:

First add in the file "Linux and OSX Installation Instructions.txt" the instruction to install DBD-SQLite for those users using sqlite!
1. I did not know what to put in the setting.config "filename=", however as section 4 asks to download the database and you instruct to load it using sqlite3, it can be a good idea to mention the relation between the database and the database file name.

1.section 1 in the "Configuration Instructions.txt" file is not clear enough yet. 
The word [optional] appears near parameters which I understand must be filled. this is confusing
1. in section 4 of the same file, the title is "Set up MySQL database backend "
   now in section 2 you point me to this section if I use SQLite, 
   It was not clear what you wanted.

Any way I have run the command:sqlite3 Model-SEED-core/data/ModelDB/ModelDB.db < Model-SEED-core/data/ModelDB/ModelDB.sqlite;

and then ran the ms-config

and got the following message.

No user account found with name: public!

I do not know if this is OK or not.
1. and finally in section 5. "Test the Model SEED"
   I ran the command as suggested but I got the following message:
   Function name must be specified as input arguments!

but what is that function name????

**Comment by cshenry** [comment]
1.) I created an entire site on configuring the model seed, and I hope I have clarified the link between "filename" and sqlite there.

2.) Again, hopefully the mysql instructions will be clearer in the new wiki.

3.) You donot need to run the sqlite3 command anymore. bootstrap.sh does this for you.

4.) The "No user account found with name: public!" error is because initially, the database has no user accounts, and the config function attempts to log in as the default account, public. I added a new message to alleviate concerns at this message.

5.) I changed the welcome message of the Model Driver to give more information. Hopefully this is clearer.
