### ISSUE TITLE
fbacheckgrowth tries to create an existing directory

### ISSUE THREAD

**Issue by levinas** [ModelSEED/Model-SEED-core#67]
I got the following error message when trying to run fbacheckgrowth. I looked for mkdir lines in the code in lib/ but could not identify which one is causing the issue.

../Model-SEED-core/bin/ModelDriver fbacheckgrowth -model "iJR904.16242"                        

Processing argument: fbacheckgrowth
Creating the model file: /lustre/beagle/fangfang/ModelSEED/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/3/iJR904.16242.tbl
Creating biochemistry provenance files
mkdir: cannot create directory `/lustre/beagle/fangfang/ModelSEED/Model-SEED-core/data/ReactionDB/MFAToolkitOutputFiles/3/MFAOutput': File exists
iJR904.16242 failed to grow in Complete media.

**Comment by jamesclulow** [comment]
I have seen the same errors as well. Also seeing iJR904 fail to grown in Complete media. This came down to errors with glpk for me. I see the following errors in the MFAtoolkit error log:
Failed to load solver because solver could not be cleared.
I reconfigured with CPLEX and now it grows fine (I'm assuming that it is running using CPLEX as opposed to glpk)
Anyone else had this problem?

**Comment by cshenry** [comment]
The system sometimes attempts to create directories when they already exist, but this isn't actually an error. We're working on getting these errors to go away.

**Comment by devoid** [comment]
Closing since it is stale.
